apiVersion: v1
kind: Service
metadata:
  name: kuberdbs
  labels:
    app: kuberdbs
spec:
  ports:
  - port: 80
    name: kuberdbs
    targetPort: 8080
  selector:
    app: kuberdbs
  type: LoadBalancer


