apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kuberdbs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuberdbs
    spec:
      containers:
      - name: kuberdbs
        image: anubhavmishra/kuberdbs:latest
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - "--redis-addr"
          - "redis.redis:6379" # change this to your redis server address
          - "--mysql-addr"
          - "mysql.mysql:3306" # change this to your mysql server address
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: rootpw