apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-sentinel-proxy
    spec:
      containers:
      - name: redis-sentinel-proxy
        image: anubhavmishra/redis-sentinel-proxy:latest
        args:
          - "-master"
          - "primary"
          - "-sentinel"
          - "redis-sentinel:26379"
        ports:
        - containerPort: 9999